const elements = [
  { number: 1, symbol: "H", name: "Hydrogen", mass: 1.008, type: "nonmetal", col: 1, row: 1 },
  { number: 2, symbol: "He", name: "Helium", mass: 4.0026, type: "noble gas", col: 18, row: 1 },

  { number: 3, symbol: "Li", name: "Lithium", mass: 6.94, type: "alkali metal", col: 1, row: 2 },
  { number: 4, symbol: "Be", name: "Beryllium", mass: 9.0122, type: "alkaline earth metal", col: 2, row: 2 },
  { number: 5, symbol: "B", name: "Boron", mass: 10.81, type: "metalloid", col: 13, row: 2 },
  { number: 6, symbol: "C", name: "Carbon", mass: 12.011, type: "nonmetal", col: 14, row: 2 },
  { number: 7, symbol: "N", name: "Nitrogen", mass: 14.007, type: "nonmetal", col: 15, row: 2 },
  { number: 8, symbol: "O", name: "Oxygen", mass: 15.999, type: "nonmetal", col: 16, row: 2 },
  { number: 9, symbol: "F", name: "Fluorine", mass: 18.998, type: "halogen", col: 17, row: 2 },
  { number: 10, symbol: "Ne", name: "Neon", mass: 20.180, type: "noble gas", col: 18, row: 2 },

  { number: 11, symbol: "Na", name: "Sodium", mass: 22.990, type: "alkali metal", col: 1, row: 3 },
  { number: 12, symbol: "Mg", name: "Magnesium", mass: 24.305, type: "alkaline earth metal", col: 2, row: 3 },
  { number: 13, symbol: "Al", name: "Aluminium", mass: 26.982, type: "post-transition metal", col: 13, row: 3 },
  { number: 14, symbol: "Si", name: "Silicon", mass: 28.085, type: "metalloid", col: 14, row: 3 },
  { number: 15, symbol: "P", name: "Phosphorus", mass: 30.974, type: "nonmetal", col: 15, row: 3 },
  { number: 16, symbol: "S", name: "Sulfur", mass: 32.06, type: "nonmetal", col: 16, row: 3 },
  { number: 17, symbol: "Cl", name: "Chlorine", mass: 35.45, type: "halogen", col: 17, row: 3 },
  { number: 18, symbol: "Ar", name: "Argon", mass: 39.948, type: "noble gas", col: 18, row: 3 },

  { number: 19, symbol: "K", name: "Potassium", mass: 39.098, type: "alkali metal", col: 1, row: 4 },
  { number: 20, symbol: "Ca", name: "Calcium", mass: 40.078, type: "alkaline earth metal", col: 2, row: 4 },

  { number: 21, symbol: "Sc", name: "Scandium", mass: 44.956, type: "transition metal", col: 3, row: 4 },
  { number: 22, symbol: "Ti", name: "Titanium", mass: 47.867, type: "transition metal", col: 4, row: 4 },
  { number: 23, symbol: "V", name: "Vanadium", mass: 50.942, type: "transition metal", col: 5, row: 4 },
  { number: 24, symbol: "Cr", name: "Chromium", mass: 51.996, type: "transition metal", col: 6, row: 4 },
  { number: 25, symbol: "Mn", name: "Manganese", mass: 54.938, type: "transition metal", col: 7, row: 4 },
  { number: 26, symbol: "Fe", name: "Iron", mass: 55.845, type: "transition metal", col: 8, row: 4 },
  { number: 27, symbol: "Co", name: "Cobalt", mass: 58.933, type: "transition metal", col: 9, row: 4 },
  { number: 28, symbol: "Ni", name: "Nickel", mass: 58.693, type: "transition metal", col: 10, row: 4 },
  { number: 29, symbol: "Cu", name: "Copper", mass: 63.546, type: "transition metal", col: 11, row: 4 },
  { number: 30, symbol: "Zn", name: "Zinc", mass: 65.38, type: "transition metal", col: 12, row: 4 },
  { number: 31, symbol: "Ga", name: "Gallium", mass: 69.723, type: "post-transition metal", col: 13, row: 4 },
  { number: 32, symbol: "Ge", name: "Germanium", mass: 72.63, type: "metalloid", col: 14, row: 4 },
  { number: 33, symbol: "As", name: "Arsenic", mass: 74.922, type: "metalloid", col: 15, row: 4 },
  { number: 34, symbol: "Se", name: "Selenium", mass: 78.971, type: "nonmetal", col: 16, row: 4 },
  { number: 35, symbol: "Br", name: "Bromine", mass: 79.904, type: "halogen", col: 17, row: 4 },
  { number: 36, symbol: "Kr", name: "Krypton", mass: 83.798, type: "noble gas", col: 18, row: 4 },

  { number: 37, symbol: "Rb", name: "Rubidium", mass: 85.468, type: "alkali metal", col: 1, row: 5 },
  { number: 38, symbol: "Sr", name: "Strontium", mass: 87.62, type: "alkaline earth metal", col: 2, row: 5 },
  { number: 39, symbol: "Y", name: "Yttrium", mass: 88.906, type: "transition metal", col: 3, row: 5 },
  { number: 40, symbol: "Zr", name: "Zirconium", mass: 91.224, type: "transition metal", col: 4, row: 5 },
  { number: 41, symbol: "Nb", name: "Niobium", mass: 92.906, type: "transition metal", col: 5, row: 5 },
  { number: 42, symbol: "Mo", name: "Molybdenum", mass: 95.95, type: "transition metal", col: 6, row: 5 },
  { number: 43, symbol: "Tc", name: "Technetium", mass: 98, type: "transition metal", col: 7, row: 5 },
  { number: 44, symbol: "Ru", name: "Ruthenium", mass: 101.07, type: "transition metal", col: 8, row: 5 },
  { number: 45, symbol: "Rh", name: "Rhodium", mass: 102.91, type: "transition metal", col: 9, row: 5 },
  { number: 46, symbol: "Pd", name: "Palladium", mass: 106.42, type: "transition metal", col: 10, row: 5 },
  { number: 47, symbol: "Ag", name: "Silver", mass: 107.87, type: "transition metal", col: 11, row: 5 },
  { number: 48, symbol: "Cd", name: "Cadmium", mass: 112.41, type: "transition metal", col: 12, row: 5 },
  { number: 49, symbol: "In", name: "Indium", mass: 114.82, type: "post-transition metal", col: 13, row: 5 },
  { number: 50, symbol: "Sn", name: "Tin", mass: 118.71, type: "post-transition metal", col: 14, row: 5 },
  { number: 51, symbol: "Sb", name: "Antimony", mass: 121.76, type: "metalloid", col: 15, row: 5 },
  { number: 52, symbol: "Te", name: "Tellurium", mass: 127.60, type: "metalloid", col: 16, row: 5 },
  { number: 53, symbol: "I", name: "Iodine", mass: 126.90, type: "halogen", col: 17, row: 5 },
  { number: 54, symbol: "Xe", name: "Xenon", mass: 131.29, type: "noble gas", col: 18, row: 5 },

  { number: 55, symbol: "Cs", name: "Caesium", mass: 132.91, type: "alkali metal", col: 1, row: 6 },
  { number: 56, symbol: "Ba", name: "Barium", mass: 137.33, type: "alkaline earth metal", col: 2, row: 6 },

  // Lanthanides (row 8)
  { number: 57, symbol: "La", name: "Lanthanum", mass: 138.91, type: "lanthanide", col: 4, row: 8 },
  { number: 58, symbol: "Ce", name: "Cerium", mass: 140.12, type: "lanthanide", col: 5, row: 8 },
  { number: 59, symbol: "Pr", name: "Praseodymium", mass: 140.91, type: "lanthanide", col: 6, row: 8 },
  { number: 60, symbol: "Nd", name: "Neodymium", mass: 144.24, type: "lanthanide", col: 7, row: 8 },
  { number: 61, symbol: "Pm", name: "Promethium", mass: 145, type: "lanthanide", col: 8, row: 8 },
  { number: 62, symbol: "Sm", name: "Samarium", mass: 150.36, type: "lanthanide", col: 9, row: 8 },
  { number: 63, symbol: "Eu", name: "Europium", mass: 151.96, type: "lanthanide", col: 10, row: 8 },
  { number: 64, symbol: "Gd", name: "Gadolinium", mass: 157.25, type: "lanthanide", col: 11, row: 8 },
  { number: 65, symbol: "Tb", name: "Terbium", mass: 158.93, type: "lanthanide", col: 12, row: 8 },
  { number: 66, symbol: "Dy", name: "Dysprosium", mass: 162.50, type: "lanthanide", col: 13, row: 8 },
  { number: 67, symbol: "Ho", name: "Holmium", mass: 164.93, type: "lanthanide", col: 14, row: 8 },
  { number: 68, symbol: "Er", name: "Erbium", mass: 167.26, type: "lanthanide", col: 15, row: 8 },
  { number: 69, symbol: "Tm", name: "Thulium", mass: 168.93, type: "lanthanide", col: 16, row: 8 },
  { number: 70, symbol: "Yb", name: "Ytterbium", mass: 173.05, type: "lanthanide", col: 17, row: 8 },
  { number: 71, symbol: "Lu", name: "Lutetium", mass: 174.97, type: "lanthanide", col: 18, row: 8 },

  // Actinides (row 9)
  { number: 89, symbol: "Ac", name: "Actinium", mass: 227, type: "actinide", col: 4, row: 9 },
  { number: 90, symbol: "Th", name: "Thorium", mass: 232.04, type: "actinide", col: 5, row: 9 },
  { number: 91, symbol: "Pa", name: "Protactinium", mass: 231.04, type: "actinide", col: 6, row: 9 },
  { number: 92, symbol: "U", name: "Uranium", mass: 238.03, type: "actinide", col: 7, row: 9 },
  { number: 93, symbol: "Np", name: "Neptunium", mass: 237, type: "actinide", col: 8, row: 9 },
  { number: 94, symbol: "Pu", name: "Plutonium", mass: 244, type: "actinide", col: 9, row: 9 },
  { number: 95, symbol: "Am", name: "Americium", mass: 243, type: "actinide", col: 10, row: 9 },
  { number: 96, symbol: "Cm", name: "Curium", mass: 247, type: "actinide", col: 11, row: 9 },
  { number: 97, symbol: "Bk", name: "Berkelium", mass: 247, type: "actinide", col: 12, row: 9 },
  { number: 98, symbol: "Cf", name: "Californium", mass: 251, type: "actinide", col: 13, row: 9 },
  { number: 99, symbol: "Es", name: "Einsteinium", mass: 252, type: "actinide", col: 14, row: 9 },
  { number: 100, symbol: "Fm", name: "Fermium", mass: 257, type: "actinide", col: 15, row: 9 },
  { number: 101, symbol: "Md", name: "Mendelevium", mass: 258, type: "actinide", col: 16, row: 9 },
  { number: 102, symbol: "No", name: "Nobelium", mass: 259, type: "actinide", col: 17, row: 9 },
  { number: 103, symbol: "Lr", name: "Lawrencium", mass: 266, type: "actinide", col: 18, row: 9 },

  // d-block continuation (row 6 & 7 gap filling)
  { number: 72, symbol: "Hf", name: "Hafnium", mass: 178.49, type: "transition metal", col: 4, row: 6 },
  { number: 73, symbol: "Ta", name: "Tantalum", mass: 180.95, type: "transition metal", col: 5, row: 6 },
  { number: 74, symbol: "W", name: "Tungsten", mass: 183.84, type: "transition metal", col: 6, row: 6 },
  { number: 75, symbol: "Re", name: "Rhenium", mass: 186.21, type: "transition metal", col: 7, row: 6 },
  { number: 76, symbol: "Os", name: "Osmium", mass: 190.23, type: "transition metal", col: 8, row: 6 },
  { number: 77, symbol: "Ir", name: "Iridium", mass: 192.22, type: "transition metal", col: 9, row: 6 },
  { number: 78, symbol: "Pt", name: "Platinum", mass: 195.08, type: "transition metal", col: 10, row: 6 },
  { number: 79, symbol: "Au", name: "Gold", mass: 196.97, type: "transition metal", col: 11, row: 6 },
  { number: 80, symbol: "Hg", name: "Mercury", mass: 200.59, type: "transition metal", col: 12, row: 6 },
  { number: 81, symbol: "Tl", name: "Thallium", mass: 204.38, type: "post-transition metal", col: 13, row: 6 },
  { number: 82, symbol: "Pb", name: "Lead", mass: 207.2, type: "post-transition metal", col: 14, row: 6 },
  { number: 83, symbol: "Bi", name: "Bismuth", mass: 208.98, type: "post-transition metal", col: 15, row: 6 },
  { number: 84, symbol: "Po", name: "Polonium", mass: 209, type: "metalloid", col: 16, row: 6 },
  { number: 85, symbol: "At", name: "Astatine", mass: 210, type: "halogen", col: 17, row: 6 },
  { number: 86, symbol: "Rn", name: "Radon", mass: 222, type: "noble gas", col: 18, row: 6 },

  { number: 87, symbol: "Fr", name: "Francium", mass: 223, type: "alkali metal", col: 1, row: 7 },
  { number: 88, symbol: "Ra", name: "Radium", mass: 226, type: "alkaline earth metal", col: 2, row: 7 },

  // d-block row 7
  { number: 104, symbol: "Rf", name: "Rutherfordium", mass: 267, type: "transition metal", col: 4, row: 7 },
  { number: 105, symbol: "Db", name: "Dubnium", mass: 268, type: "transition metal", col: 5, row: 7 },
  { number: 106, symbol: "Sg", name: "Seaborgium", mass: 269, type: "transition metal", col: 6, row: 7 },
  { number: 107, symbol: "Bh", name: "Bohrium", mass: 270, type: "transition metal", col: 7, row: 7 },
  { number: 108, symbol: "Hs", name: "Hassium", mass: 277, type: "transition metal", col: 8, row: 7 },
  { number: 109, symbol: "Mt", name: "Meitnerium", mass: 278, type: "transition metal", col: 9, row: 7 },
  { number: 110, symbol: "Ds", name: "Darmstadtium", mass: 281, type: "transition metal", col: 10, row: 7 },
  { number: 111, symbol: "Rg", name: "Roentgenium", mass: 282, type: "transition metal", col: 11, row: 7 },
  { number: 112, symbol: "Cn", name: "Copernicium", mass: 285, type: "transition metal", col: 12, row: 7 },
  { number: 113, symbol: "Nh", name: "Nihonium", mass: 286, type: "post-transition metal", col: 13, row: 7 },
  { number: 114, symbol: "Fl", name: "Flerovium", mass: 289, type: "post-transition metal", col: 14, row: 7 },
  { number: 115, symbol: "Mc", name: "Moscovium", mass: 290, type: "post-transition metal", col: 15, row: 7 },
  { number: 116, symbol: "Lv", name: "Livermorium", mass: 293, type: "post-transition metal", col: 16, row: 7 },
  { number: 117, symbol: "Ts", name: "Tennessine", mass: 294, type: "halogen", col: 17, row: 7 },
  { number: 118, symbol: "Og", name: "Oganesson", mass: 294, type: "noble gas", col: 18, row: 7 }
];
